import { test, expect, type Page } from '@playwright/test'

test('demo messaging, search, saved messages and settings work', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Your conversations. Yours only.' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('A private little test message')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('.message-bubble').filter({ hasText: 'A private little test message' })).toBeVisible()
  await page.getByRole('button', { name: 'Search this conversation', exact: true }).click()
  await page.getByRole('textbox', { name: 'Search messages', exact: true }).fill('private little')
  await expect(page.locator('.message-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Close message search' }).click()
  const bubble = page.locator('.message-row').filter({ hasText: 'A private little test message' })
  await bubble.hover()
  await bubble.getByRole('button', { name: 'Save message', exact: true }).click()
  await page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('button', { name: 'Saved messages' }).click()
  await expect(page.locator('.saved-card').filter({ hasText: 'A private little test message' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Preferences', exact: true }).getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('switch', { name: 'Hide message previews', exact: true }).click()
  await page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('button', { name: 'Messages', exact: false }).first().click()
  await expect(page.getByText('Message preview hidden').first()).toBeVisible()
})

test('toolkit encrypts and decrypts a note entirely locally', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: 'Main navigation', exact: true }).getByRole('button', { name: 'Privacy toolkit', exact: false }).click()
  await page.getByRole('button', { name: 'Text lock', exact: false }).click()
  await page.getByLabel('Your message', { exact: true }).fill('A secret in a local vault')
  await page.getByLabel('Passphrase', { exact: true }).fill('a long test passphrase 123')
  await page.getByRole('button', { name: 'Encrypt text', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Tool result', exact: true })).toBeVisible()
  const box = await page.getByRole('textbox', { name: 'Tool result', exact: true }).inputValue()
  expect(box).not.toContain('A secret in a local vault')
  await page.getByRole('button', { name: 'Decrypt', exact: true }).click()
  await page.getByLabel('Encrypted vault data', { exact: true }).fill(box)
  await page.getByRole('button', { name: 'Decrypt text', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Tool result', exact: true })).toHaveValue('A secret in a local vault')
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
})

test('mobile navigation and composer have no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Messages', exact: true })).toBeVisible()
  await page.locator('.conversation-item').filter({ hasText: 'Sofia Chen' }).click()
  await expect(page.getByRole('textbox', { name: 'Message', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Message', exact: true }).fill('Hello from Android-sized screens')
  await page.getByRole('button', { name: 'Send message', exact: true }).click()
  await expect(page.locator('.message-bubble').filter({ hasText: 'Hello from Android-sized screens' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Back to conversations', exact: true }).click()
  await page.getByRole('navigation', { name: 'Mobile navigation', exact: true }).getByRole('button', { name: 'Toolkit', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'A little more peace of mind.', exact: true })).toBeVisible()
})

async function signup(page: Page, name: string, username: string) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Make it yours', exact: true }).click()
  await page.getByLabel('Your name', { exact: true }).fill(name)
  await page.getByLabel('Username', { exact: true }).fill(username)
  await page.getByLabel('Passphrase', { exact: true }).fill('e2e secret passphrase 2026')
  await page.getByLabel('Confirm passphrase', { exact: true }).fill('e2e secret passphrase 2026')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Create your free account', exact: true }).click()
  await expect(page.locator('.auth-modal')).toBeHidden({ timeout: 30000 })
  await expect(page.locator('.connection-badge')).toHaveText('Connected', { timeout: 20000 })
}

test('two accounts exchange encrypted live messages, upload photos, verify keys, and unlock after locking', async ({ browser }) => {
  const aContext = await browser.newContext(), bContext = await browser.newContext()
  try {
    const a = await aContext.newPage(), b = await bContext.newPage()
    const suffix = Date.now().toString(36)
    const alice = `alice_${suffix}`, bob = `bob_${suffix}`
    await signup(a, 'Alice Test', alice)
    await signup(b, 'Bob Test', bob)
    await a.getByRole('button', { name: 'New conversation', exact: true }).click()
    await a.getByRole('textbox', { name: 'Find contact by username', exact: true }).fill(bob)
    await a.locator('.contact-result').filter({ hasText: 'Bob Test' }).click()
    await a.getByRole('textbox', { name: 'Message', exact: true }).fill('Real encrypted hello from Alice')
    await a.getByRole('button', { name: 'Send message', exact: true }).click()
    await expect(b.locator('.conversation-item').filter({ hasText: 'Alice Test' })).toBeVisible({ timeout: 20000 })
    await b.locator('.conversation-item').filter({ hasText: 'Alice Test' }).click()
    await expect(b.locator('.message-bubble').filter({ hasText: 'Real encrypted hello from Alice' })).toBeVisible()
    await b.getByRole('textbox', { name: 'Message', exact: true }).fill('And an encrypted reply from Bob')
    await b.getByRole('button', { name: 'Send message', exact: true }).click()
    await expect(a.locator('.message-bubble').filter({ hasText: 'And an encrypted reply from Bob' })).toBeVisible({ timeout: 10000 })
    await a.locator('input[type=file][accept="image/jpeg,image/png,image/webp"]').setInputFiles('web/public/images/alpine-lake.jpg')
    await expect(a.locator('.attachment-preview')).toBeVisible({ timeout: 20000 })
    await a.getByRole('button', { name: 'Send message', exact: true }).click()
    await expect(b.locator('.message-photo img')).toBeVisible({ timeout: 10000 })
    if (!await a.locator('.conversation-details').isVisible()) await a.getByRole('button', { name: 'Conversation details', exact: true }).click()
    await a.locator('.contact-quick-actions').getByRole('button', { name: 'Verify', exact: true }).click()
    await expect(a.locator('.fingerprint-grid code')).toHaveCount(16)
    await a.getByRole('checkbox').check()
    await a.getByRole('button', { name: 'Mark identity as verified', exact: true }).click()
    const storage = await a.evaluate(() => JSON.stringify(localStorage))
    expect(storage).not.toContain('Real encrypted hello from Alice')
    expect(storage).not.toContain('And an encrypted reply from Bob')
    await a.getByRole('button', { name: 'Lock your account', exact: true }).click()
    await expect(a.getByRole('heading', { name: 'Welcome back.', exact: true })).toBeVisible()
    await a.getByLabel('Passphrase', { exact: true }).fill('e2e secret passphrase 2026')
    await a.getByRole('button', { name: 'Unlock your space', exact: true }).click()
    await expect(a.locator('.conversation-item').filter({ hasText: 'Bob Test' })).toBeVisible({ timeout: 20000 })
    await a.locator('.conversation-item').filter({ hasText: 'Bob Test' }).click()
    await expect(a.locator('.message-bubble').filter({ hasText: 'And an encrypted reply from Bob' })).toBeVisible()
  } finally { await aContext.close().catch(() => {}); await bContext.close().catch(() => {}) }
})
